
services:
  app:
    build:
      context: .
    container_name: mad-app
    volumes:
      - .:/app                   # project source
      - uv_venv:/root/.uv        # container-only uv venv
    stdin_open: true
    tty: true

volumes:
  uv_venv:


